[package]
name = "summarizer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-openai = "0.16.3"
axum = "0.6.20"
rust-embed = "8.0.0"
shuttle-axum = "0.34.0"
shuttle-runtime = "0.34.0"
shuttle-secrets = "0.34.0"
tokio = "1.28.2"
tracing = "0.1.40"
